import type { MenuItem } from './types';

const P1 = '/images/menu/ChatGPT_Image_15_lug_2026,_15_02_00 copy.png';
const P2 = '/images/menu/ChatGPT_Image_15_lug_2026,_15_03_18 copy.png';
const DS = '/images/desserts/WhatsApp_Image_2026-07-15_at_14.19.15.jpeg';
const BK = '/images/craft-beers/ChatGPT_Image_15_lug_2026,_15_04_59 copy.png';

export const menuItems: MenuItem[] = [
  // ─── Pizze ────────────────────────────────────────────────
  {
    id: 'margherita',
    name: 'Margherita',
    description: 'La classica pizza napoletana, semplice e perfetta.',
    ingredients: 'Pomodoro San Marzano, fiordilatte, basilico fresco',
    price: 5,
    category: 'pizze',
    image: P1,
    badge: 'Classica',
  },
  {
    id: 'marinara',
    name: 'Marinara',
    description: 'Senza formaggio — il sapore autentico del mare.',
    ingredients: 'Pomodoro San Marzano, aglio, origano, olio EVO',
    price: 5,
    category: 'pizze',
    image: P2,
    badge: 'Classica',
  },
  {
    id: 'diavola',
    name: 'Diavola',
    description: 'Per gli amanti del piccante, avvolgente e intensa.',
    ingredients: 'Pomodoro, fiordilatte, salame piccante calabrese',
    price: 8,
    category: 'pizze',
    image: P1,
    badge: 'Piccante',
  },
  {
    id: 'capricciosa',
    name: 'Capricciosa',
    description: 'Ricca di ingredienti selezionati per un gusto completo.',
    ingredients: 'Pomodoro, fiordilatte, funghi, prosciutto cotto, olive, carciofi',
    price: 9,
    category: 'pizze',
    image: P2,
    badge: 'Classica',
  },
  {
    id: 'partenope',
    name: 'Partenope',
    description: 'Ricetta della tradizione napoletana più autentica.',
    ingredients: 'Ricetta originale della tradizione partenopea',
    price: 8,
    category: 'pizze',
    image: P1,
    badge: 'Speciale',
  },
  {
    id: 'bufalina',
    name: 'Bufalina',
    description: 'Con l\'eccellenza della mozzarella di bufala DOP.',
    ingredients: 'Pomodoro San Marzano, mozzarella di bufala campana DOP, basilico fresco',
    price: 9,
    category: 'pizze',
    image: P2,
    badge: 'Speciale',
  },
  {
    id: '5-formaggi',
    name: '5 Formaggi',
    description: 'Un viaggio attraverso cinque formaggi italiani selezionati.',
    ingredients: 'Fiordilatte, scamorza, gorgonzola, parmigiano reggiano, provola',
    price: 9,
    category: 'pizze',
    image: P1,
    badge: 'Speciale',
  },
  {
    id: 'ortolana',
    name: 'Ortolana',
    description: 'Verdure di stagione grigliate per un piatto vegetariano d\'eccellenza.',
    ingredients: 'Pomodoro, fiordilatte, verdure miste di stagione grigliate',
    price: 10,
    category: 'pizze',
    image: P2,
    badge: 'Veggie',
  },
  {
    id: 'bronte',
    name: 'Bronte',
    description: 'Il profumo di Sicilia incontra la pizza napoletana.',
    ingredients: 'Crema di pistacchio di Bronte DOP, fiordilatte, mortadella di Bologna IGP',
    price: 10,
    category: 'pizze',
    image: P1,
    badge: 'Gourmet',
  },
  {
    id: 'tartufina',
    name: 'Tartufina',
    description: 'Per i palati più raffinati — un\'esperienza sensoriale unica.',
    ingredients: 'Fiordilatte, tartufo nero, porcini trifolati, olio al tartufo',
    price: 12,
    category: 'pizze',
    image: P2,
    badge: 'Gourmet',
  },
  {
    id: 'delizia-irpinia',
    name: 'Delizia Irpinia',
    description: 'Il meglio dell\'Irpinia in ogni morso.',
    ingredients: 'Salsiccia irpina, friarielli, provola affumicata',
    price: 12,
    category: 'pizze',
    image: P1,
    badge: 'Gourmet',
  },
  {
    id: 'partenio',
    name: 'Partenio 2.0',
    description: 'L\'interpretazione della casa con ingredienti selezionati.',
    ingredients: 'Interpretazione esclusiva della casa, ingredienti del territorio',
    price: 12,
    category: 'pizze',
    image: P2,
    badge: 'Gourmet',
  },
  {
    id: 'crocco',
    name: 'Crocco Pizza',
    description: 'Pizza ripiena cotta nel forno a legna.',
    ingredients: 'Ripieno della casa, ricotta, cicoli, pepe — forno a legna',
    price: 10,
    category: 'pizze',
    image: P1,
    badge: 'Ripieno',
  },
  {
    id: 'pizza-pazza',
    name: 'Pizza Pazza',
    description: 'Il calzone irresistibile della tradizione.',
    ingredients: 'Ricotta fresca, cicoli napoletani, pepe nero macinato',
    price: 10,
    category: 'pizze',
    image: P2,
    badge: 'Ripieno',
  },

  // ─── Dolci ────────────────────────────────────────────────
  { id: 'rocher', name: 'Rocher', description: 'Croccante e avvolgente, irresistibile ad ogni morso.', price: 5, category: 'dolci', image: DS },
  { id: 'porcellino', name: 'Porcellino Rosa', description: 'Dolcezza irresistibile, il preferito dei bambini.', price: 5, category: 'dolci', image: DS },
  { id: 'mela', name: 'Mela Caramellata', description: 'Fresca e croccante, un classico rivisitato.', price: 5, category: 'dolci', image: DS },
  { id: 'pistacchio-dolce', name: 'Pistacchio', description: 'Crema di pistacchio di Bronte DOP.', price: 5, category: 'dolci', image: DS },
  { id: 'cheesecake', name: 'Cheesecake', description: 'Morbida e cremosa, un dessert intramontabile.', price: 5, category: 'dolci', image: DS },
  { id: 'tortino', name: 'Tortino al Cioccolato', description: 'Cuore caldo fondente — servito tiepido.', price: 5, category: 'dolci', image: DS },
  { id: 'cookie', name: 'Cookie Cream', description: 'Friabile e goloso, perfetto per i golosi.', price: 5, category: 'dolci', image: DS },
  { id: 'millefoglie', name: 'Millefoglie', description: 'Pasta sfoglia e crema pasticcera artigianale.', price: 5, category: 'dolci', image: DS },

  // ─── Birre & Drinks ───────────────────────────────────────
  { id: 'scuba', name: 'Scuba Diaborupel', description: 'Quadrupel belga artigianale — note di caramello e spezie.', price: 5, category: 'birre', image: BK, badge: 'Artigianale' },
  { id: 'leffe', name: 'Leffe Blonde', description: 'Birra abbaziale belga con aromi fruttati e agrumi.', price: 4, category: 'birre', image: BK, badge: 'Belgio' },
  { id: 'franziskaner', name: 'Franziskaner', description: 'Classica Weissbier bavarese — banana e chiodi di garofano.', price: 4, category: 'birre', image: BK, badge: 'Germania' },
  { id: 'corona', name: 'Corona Extra', description: 'Lager messicana leggera — perfetta con limone.', price: 4, category: 'birre', image: BK, badge: 'Messico' },
  { id: 'selezione', name: 'Selezione del Giorno', description: 'Birra artigianale del giorno — chiedi al cameriere.', price: 5, category: 'birre', image: BK, badge: 'Speciale' },
  { id: 'acqua-nat', name: 'Acqua Naturale', description: 'Bottiglia da 0.5L.', price: 1.5, category: 'birre', image: BK },
  { id: 'acqua-frz', name: 'Acqua Frizzante', description: 'Bottiglia da 0.5L.', price: 1.5, category: 'birre', image: BK },
  { id: 'coca', name: 'Coca-Cola', description: 'Lattina 33cl.', price: 2.5, category: 'birre', image: BK },
  { id: 'fanta', name: 'Fanta', description: 'Lattina 33cl.', price: 2.5, category: 'birre', image: BK },
  { id: 'sprite', name: 'Sprite', description: 'Lattina 33cl.', price: 2.5, category: 'birre', image: BK },
  { id: 'vino', name: 'Vino della Casa', description: 'Rosso o Bianco — calice.', price: 4, category: 'birre', image: BK },
];
